
title: MSChamarthy | Resume
url: 'http://mschamarthy.com'
baseurl: '/resume' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Mohan Chamarthy
tagline: Data Analyst <br>Big Data Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: hello@mschamarthy.com
hire-me-email: hire.me@mschamarthy.com
phone: 773 245 6592
website: mschamarthy.com #do not add http://
linkedin: mschamarthy
github: mschamarthy
twitter: ''


# Tracker
analytics: UA-108887155-1
#Update all the sections by editing the files inside _includes folder.
